djangogoat/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.views.generic import TemplateView
from django.views.static import serve
from django.urls import (
    include,
    path,
    re_path,
)

from authentication import views as auth_views
from notes import views as notes_views


urlpatterns = [
    path('admin/', admin.site.urls),

    # Notes pages
    path('dash/', notes_views.dash, name='dash'),
    path(
        'conversation/<friend_pk>',
        notes_views.conversation,
        name='conversation'
    ),
    path('note/<pk>', notes_views.note, name='note'),
    path('write-note/', notes_views.write_note, name='write-note'),

    # Unauthenticated pages
    path('vulnerabilities',
         TemplateView.as_view(template_name='vulnerabilities.html'),
         name='vulnerabilities'),
    path(
        '',
        TemplateView.as_view(template_name='landing.html'),
        name='landing'
    ),
    path(
        'instructions',
        TemplateView.as_view(template_name='instructions.html'),
        name='instructions'
    ),

    # Authentication and user management pages
    path('login/', auth_views.log_in, name='login'),
    path('logout/', logout_then_login, {'login_url': 'login'}, name='logout'),
    path('profile/<pk>', auth_views.profile, name='profile'),
    path('profile-update', auth_views.profile_update, name='profile-update'),
    path('sign-up/', auth_views.sign_up, name='sign-up'),
    path('', include('django.contrib.auth.urls')),

    # Media files
    re_path(
        r'^media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
]

authentication/models.py
import os

from django.db import models


def upload_path(user, filename):
    extension = os.path.splitext(filename)[1]
    return 'avatar_%s%s' % (user.pk, extension)


class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=upload_path, blank=True)
    bio = models.TextField(max_length=255, blank=True)

common/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    An abstract base class model which provides self-updating 'created' and
    'modified' fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

notes/models.py
from django.db import models

from common.models import TimeStampedModel


class Note(TimeStampedModel):
    sender = models.ForeignKey(
        'auth.User',
        on_delete=models.PROTECT,
        related_name='sender'
    )
    receiver = models.ForeignKey(
        'auth.User',
        on_delete=models.PROTECT,
        related_name='receiver'
    )
    content = models.TextField(max_length=255)

    class Meta:
        ordering = ['created']

authentication/forms.py
from django import forms

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'bio')
        widgets = {
            'avatar': forms.FileInput(),
            'bio': forms.Textarea(attrs={'rows': 5}),
        }

notes/forms.py
from django import forms

from .models import Note


class WriteNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('content', 'receiver')
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5}),
        }

authentication/views.py
from django.contrib.auth import (
    authenticate,
    login,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)

from common.decorators import public
from .forms import UserProfileForm
from .models import UserProfile


@public
def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            UserProfile.objects.create(user=new_user)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('profile', pk=user.pk)
    else:
        form = UserCreationForm()

    return render(request, 'sign_up.html', {'form': form})


@public
def log_in(request):
    error = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('dash')
        else:
            error = 'The credentials you entered are not valid. Try again.'

    return render(request, 'login.html', {'error': error})


@login_required
def profile_update(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(
            request.POST,
            request.FILES,
            instance=user.userprofile
        )
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            return redirect('profile', pk=user.pk)
    else:
        form = UserProfileForm(instance=user.userprofile)

    return render(request, 'profile_update.html', {
     'form': form,
     'user': user,
    })


@login_required
def profile(request, pk):
    target_user = get_object_or_404(User, pk=pk)

    return render(request, 'profile.html', {'target_user': target_user})

notes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)

from .forms import (
    WriteNoteForm,
    ReplyForm
)
from .models import Note


@login_required
def dash(request):
    all_notes = Note.objects.\
        filter(Q(sender=request.user) | Q(receiver=request.user))

    friends_pks = set()
    for sender, receiver in all_notes.values_list('sender', 'receiver'):
        friends_pks.add(sender)
        friends_pks.add(receiver)

    latest_notes = []
    for friend_pk in friends_pks:
        if friend_pk == request.user.pk:
            conversation = all_notes.\
                filter(sender=request.user).\
                filter(receiver=request.user)
        else:
            conversation = all_notes.\
                filter(Q(receiver__pk=friend_pk) | Q(sender__pk=friend_pk))
        if conversation:
            latest_note = conversation.last()
            latest_notes.append(latest_note)

    return render(request, 'dash.html', {'latest_notes': latest_notes})


@login_required
def write_note(request):
    user = request.user
    if request.method == 'POST':
        form = WriteNoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.sender = user
            note.save()
            return redirect('dash')
    else:
        form = WriteNoteForm()
    return render(request, 'write_note.html', {'form': form})


@login_required
def note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    if request.user not in [note.sender, note.receiver]:
        raise Http404()
    return render(request, 'note.html', {'note': note})


@login_required
def conversation(request, friend_pk):
    friend = get_object_or_404(User, pk=friend_pk)
    friend_name = friend.username
    all_notes = Note.objects.\
        filter(Q(sender=request.user) | Q(receiver=request.user))
    if friend == request.user:
        conversation = all_notes.\
            filter(sender=request.user).\
            filter(receiver=request.user)
    else:
        conversation = all_notes.\
            filter(Q(receiver__pk=friend_pk) | Q(sender__pk=friend_pk))

    user = request.user
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.sender = user
            note.receiver = friend
            note.save()
            return redirect('conversation', friend_pk=friend_pk)
    else:
        form = WriteNoteForm()

    return render(request, 'conversation.html', {
        'conversation': conversation,
        'form': form,
        'friend_name': friend_name,
    })

authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block pagename %}Log In{% endblock pagename %}


{% block content %}
<form method='post' class="pa4 black-80 measure center">
  <fieldset id="sign_up" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Log In</legend>
    <small id="error" class="f6 black-60 db mv2">
      {{ error }}
    </small>
  {% csrf_token %}
  <div class='mt3'>
    <label for='id_username' class="db fw6 lh-copy f6">Username</label>
    <input type='text' id='id_username' name='username'
      class="b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2"
      required autofocus>
  </div>
  <div class='mt3'>
    <label for='id_password' class="db fw6 lh-copy f6">Password</label>
    <input type='password' id='id_password' name='password'
      class="b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2"
      autocomplete='off' required>
  </div>
  <div class="">
    <button class="b ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id="login_button" type="submit">
      Log in
    </button>
  </div>
</form>
{% endblock content %}

authentication/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block pagename %}Profile {% endblock pagename %}


{% block content %}
<article class="w-third-l w-50-m w-100 center br3 pa3 pa4-ns mv3 ba b--white-30">
  <div class="tc">
    {% if target_user.userprofile.avatar %}
    <img src="{% get_media_prefix %}{{ target_user.userprofile.avatar }}"
        class="br-100 h4 w4 dib" title="picture of a goat">
    {% else %}
    <img src="/static/unknown_goat.png" class="br-100 h4 w4 dib"
      title="Black shillouette of a goat with a pink question mark">
    {% endif %}
    <h1 class="f4">{{ target_user.username }}</h1>
    <hr class="mw3 bb bw1 b--white-40">
  <p class="lh-copy measure center f6 black-70">
    {{ target_user.userprofile.bio }}
  </p>
  {% if target_user == request.user %}
    <a class="center tc mt2 f7 link bg-animate white hover-near-black hover-bg-lightest-blue dib pv2 ph3 br-pill ba b--white-20"
       href="{% url 'profile-update' %}">Edit Profile</a>
  {% endif %}
</div>
</article>
{% endblock content %}

authentication/templates/profile_update.html
{% extends 'base.html' %}
{% load setclass %}

{% block pagename %}Profile Update{% endblock pagename %}

{% block content %}
<form enctype='multipart/form-data' method='post'
  class="pa4 black-80 measure center">
  <fieldset id="profile" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Profile update</legend>
  {% csrf_token %}
  <div class='mt3 w-100'>
    <label for='id_avatar' class="db fw6 lh-copy f6">Avatar</label>
      {{ form.avatar | setclass:'w-100 mb2'}}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
    </div>
  </div>
  <div class='mt3'>
    <label for='id_bio' class="db fw6 lh-copy f6">Bio</label>
      {{ form.bio | setclass:'db border-box w-100 measure ba b--white-40 pa2 mb2'}}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class="">
    <input class="b mt2 ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id='update' type="submit" value="Update">
  </div>
</form>
{% endblock content %}

authentication/templates/sign_up.html
{% extends 'base.html' %}
{% load setclass_rm_autocomplete %}
{% load setclass %}
{% block pagename %}Sign Up{% endblock pagename %}


{% block content %}
<form method='post' class="pa4 black-80 measure center">
  <fieldset id="sign_up" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Sign Up</legend>
  {% csrf_token %}
  <div class='mt3'>
    <label for='username' class="db fw6 lh-copy f6">Username</label>
      {{ form.username |setclass:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.username.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class='mt3'>
    <label for='id_password1' class="db fw6 lh-copy f6">Password</label>
      {{ form.password1|setclass_rm_autocomplete:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.password1.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class='mt3'>
    <label for='id_password2' class="db fw6 lh-copy f6">Password Confirmation</label>
      {{ form.password2|setclass_rm_autocomplete:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.password2.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class="">
    <input class="b mt2 ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id='submit_button' type="submit" value="Sign Up">
  </div>
</form>
{% endblock content %}

common/templates/403_csrf.html
{% extends 'base.html' %}
{% load static %}

{% block pagename %}403{% endblock pagename %}


{% block content %}
<header class="near-black tc pv3 avenir">
  <h1 class="mt2 mb0 baskerville i fw1 f1">403 CSRF</h1>
  <p class="center bb b--white-50 w-50 mt4"></p>
</header>
{% endblock content %}

common/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="stylesheet" href="{% static '/css/tachyons-4.11.1.min.css' %}"/>
    <title>DjangoGoat | {% block pagename %}{% endblock pagename %}</title>

  </head>

  <body class="bg-light-pink near-black">

<!-- NAVBAR
===================================== -->
<nav class="flex justify-between bb b--white-10">
  <div class="flex-grow pa3 flex items-center">
    <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-lightest-blue dib pa3 ph4-l"
    href="{% url 'landing' %}">Home</a>
    <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-light-green dib pa3 ph4-l"
    href="https://github.com/red-and-black/djangogoat" target='_blank'>Code</a>
    <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-light-yellow dib pa3 ph4-l"
    href="/vulnerabilities">Vulnerabilities</a>
    <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-near-white dib pa3 ph4-l"
    href="/instructions">Instructions</a>
    {% if user.is_authenticated %}
    <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-washed-red dib pa3 ph4-l"
    href="/dash">Dash</a>
    {% endif %}
  </div>
  <div class="flex-grow pa3 flex items-center">
    {% if user.is_authenticated %}
      <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-light-blue dib pa3 ph4-l" href="{% url 'logout' %}">
        <i class='fa fa-lg fa-user'></i>
          &nbsp;{{ user.username }} | Log Out
      </a>
    {% else %}
      <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-light-blue dib pa3 ph4-l"
        href="{% url 'login' %}">Log In</a>
      <a class="f6 f5-l link bg-animate white hover-near-black hover-bg-light-yellow dib pa3 ph4-l"
        href="{% url 'sign-up' %}">Sign Up</a>
    {% endif %}
  </div>
</nav>



<!-- CONTENT
===================================== -->
    {% block content %}
    {% endblock content %}
  </body>
</html>

common/templates/bugs.html
{% extends 'base.html' %}
{% load static %}

{% block pagename %}Vulnerabilities{% endblock pagename %}


{% block content %}
<header class="near-black tc pv3 avenir">
  <h1 class="mt2 mb0 baskerville i fw1 f1">Vulnerabilities</h1>
  <p class="center bb b--white-50 w-50 mt4"></p>
  <p class="center w-50 mt4">
    Even in the 'good' version of our app we have a couple of vulnerabilities.
    ZAP will not pick these up, but they are there - a good example of why you
    need to know a little about common issues, and not rely only on automated
    tools.
  </p>
  <p class="center w-50 mt4">
    In addition to these vulnerbailities, this version of the app will show some
    ZAP alerts if you scan it.
  </p>
  <p class="center w-50 mt4">
    These are 'Cookie No HttpOnly Flag' and 'Cookie without Secure Flag'.
    They relate to the 'sessionid' cookie on the log out page. They occur because
    when Django logs a user out, the sessionid cookie is replaced with an empty
    string, and has no flags set. This isn't a security problem (see the explanation
    <a href='https://stackoverflow.com/a/33787443' class='link dim'>here</a>).
  </p>
  <p class="center w-50 mt4">
    You may also come across alerts for SQL injection. We've tried our best to
    exploit this, but it seems to us it is a false positive. If you can figure
    it out, let us know!
  </p>
</header>
<div class='center w-50-ns w-100'>
  <article class="center mw5 mw6-ns hidden ba b--white mv4">
    <h3 class="f7 bg-transparent near-black mv0 pv2 ph3 ba b--white">A2 OWASP</h3>
    <h2 class="f5 bg-white near-black mv0 pv2 ph3">Vulnerable authentication</h2>
    <div class="pa3 bt b--white">
      <h3 class='f6'>Where</h3>
      <p class="f6 lh-copy measure mv0">
        Log in page
      </p>
      <h3 class='f6'>Details</h3>
      <p class="f6 lh-copy measure mv0">
        The app has no rate limiting on the log in page and doesn't use
        multi-factor authentication.
        Rate limiting and multi-factor aren't built in to Django, and we did
        not build one ourselves due to time constraints. In a real app these
        should be addressed.
      </p>
      <h3 class='f6'>Possible exploitation</h3>
      <p class="f6 lh-copy measure mv0">
        This app is open to brute force and credential stuffing authentication
        attacks. A malicious user or bot could try to guess a legitmate user's
        password as many times as they need to until they succeed.
      </p>
      <p class="f6 lh-copy measure mv0">
        <b>OWASP Top 10 reference:</b>
        <a href="https://www.owasp.org/index.php/Top_10-2017_A2-Broken_Authentication"
          class='link dim'>
          A2-Broken Authentication
        </a>
      </p>
    </div>
  </article>
  <article class="center mw5 mw6-ns hidden ba b--white mv4">
    <h3 class="f7 bg-transparent near-black mv0 pv2 ph3 ba b--white">A10 OWASP</h3>
    <h2 class="f5 bg-white near-black mv0 pv2 ph3">Insufficient logging and monitoring</h2>
    <div class="pa3 bt b--white">
      <h3 class='f6'>Where</h3>
      <p class="f6 lh-copy measure mv0">
        Admin
      </p>
      <h3 class='f6'>Details</h3>
      <p class="f6 lh-copy measure mv0">
        This app has no logging and monitoring.
        Attackers rely on insufficient logging and monitoring to have time to
        conduct other attacks before the owner notices.
      </p>
      <h3 class='f6'>Possible exploitation</h3>
      <p class="f6 lh-copy measure mv0">
        For example, in this app there is also no rate limiting on the log in page.
        Because there is insufficient logging and monitoring, the app owner would
        not notice a brute force attack unless they happened to be watching at that
        exact moment.
      </p>
      <p class="f6 lh-copy measure mv0">
        <b>OWASP Top 10 reference:</b>
        <a href="https://www.owasp.org/index.php/Top_10-2017_A10-Insufficient_Logging%26Monitoring"
          class='link dim'>
          A10-Insufficient Logging and Montioring
        </a>
      </p>
    </div>
  </article>
</div>
{% endblock content %}

common/templates/instructions.html
{% extends 'base.html' %}
{% load static %}

{% block pagename %}Instructions{% endblock pagename %}

{% block content %}
<header class="near-black tc pv3 avenir">
  <h1 class="mt2 mb0 baskerville i fw1 f1">Instructions</h1>
  <p class="center bb b--white-50 w-50 mt4"></p>
</header>
<div class='center w-50-ns w-100'>
  <p class='near-black'>
    DjangoGoat is an intentionally vulnerable Django application with a test
    suite which includes automated pentests using the ZAP security testing tool.
  </p>
  <p class='near-black'>It's aim is to demonstrate:</p>
  <ul>
    <li class='pv1'>
      How to find and fix common web application security vulnerabilities, and
    </li>
    <li class='pv1'>
      How to integrate automated pentesting into a BDD test suite.
    </li>
  </ul>
  <p class='near-black'>
    The DjangoGoat repo has two branches: <i>master</i> and
    <i>broken</i>.
  </p>
  <p class='near-black'>
    The <i>master</i> branch contains the app and tests, with no
    vulnerabilities deliberately introduced (although there are a few
    weaknesses like a lack of rate-limiting on the login page, and a lack of
    monitoring, the fixing of which we decided was outside the scope of this
    simple demonstration app).
  </p>
  <p class='near-black'>
    The <i>broken</i> branch contains the app and tests, and contains a
    number of additional commits, each of which introduces a different security
    vulnerability.
  </p>
  <h2>
    Notes
  </h2>
  <ul>
    <li class='pv1'>
      When switching between branches or commits, please note you may need
      to rerun migrations.
    </li>
    <li class='pv1'>
      Very occasionally the BDD tests will not run. We think this is caused by
      a timing issue. Just Ctrl + C, and try again.
    </li>
    <li class='pv1'>
      As you progress through the 'borken' commits, some BDD tests will fail.
      This is expected behavior.
    </li>
  </ul>
  <h2>
    Exercise 1: Run the test suite
  </h2>
  <p class='near-black'>
    On the <i>broken</i> branch, run the BDD test suite using the
    instructions in the README.
  </p>
  <p class='near-black'>
    Once the tests have completed, read over the report which ZAP generated.
    It'll be called 'report.html', and be in the same directory from which you
    start the tests.
  </p>
  <p class='near-black'>
    If you're interested to see what ZAP finds on the <i>broken</i> branch
    that it doesn't find on the <i>master</i> branch, run the tests on the
    <i>master</i> branch as well.
  </p>
  <h2>
    Exercise 2: Code review for vulnerabilities
  </h2>
  <p class='near-black'>
    Do a <i>checkout</i> of the <i>broken</i> branch.
  </p>
  <p class='near-black'>
    Read the diff of each commit after it diverges from the <i>master</i>
    branch to understand how each vulnerability is created.
  </p>
  <h2>
    Exercise 3: Exploit vulnerabilities manually
  </h2>
  <p class='near-black'>
    On the <i>broken</i> branch, try these attacks:
  </p>
  <ol>
  <li class='pv1'>
    Log in without a password using SQL injection
    <ul>
      <li class='pv1'>Enter a username for a valid user, in the username field.</li>
      <li class='pv1'>Enter the string "' OR '1'='1" in the password field.</li>
    </ul>
  </li>
  <li class='pv1'>
    Perform a cross-site scripting attack from one user on another user
    <ul>
      <li class='pv1'>On the write-note or conversation page, select a user to write to.</li>
      <li class='pv1'>
        In the content section of the note, include the following script:
        <p>"&lt;script&gt;alert(‘XSS Attack’)&lt;/script&gt;"</p>
      </li>
    </ul>
  </li>
  <li class='pv1'>
    Use URL enumeration to access a page the user you're logged in as
    shouldn't see
    <ul>
      <li class='pv1'>Browse to a note between you and another user.</li>
      <li class='pv1'>
        Change the pk in the url to another note number (choosing a low number
        is a good idea).
      </li>
      <li class='pv1'>
        Repeat until you see a note from another user (on the `broken` branch).
      </li>
    </ul>
  </li>
  <li class='pv1'>
    Find a stacktrace by visiting a non-existant URL
  </li>
  <li class='pv1'>
    Use ZAP to attack the login form using credential stuffing
    (optional task)
    <ul>
      <li class='pv1'><a href='https://groups.google.com/forum/#!topic/zaproxy-users/P3hFcY_eXUk'>
        This link explains how.
      </a></li>
    </ul>
  </li>
  </ol>
  <h2>
    Exercise 4: Code review for ZAP integration
  </h2>
  <p class='near-black'>
    On either branch, read and understand the diff for the commit called
    "Add ZAP security scanning".
  </p>
  <p class='near-black'>
    This commit represents all the code you need to add automated pentesting
    into a project which has an existing BDD test suite based on Behave and
    Selenium.
  </p>
  <h2>
    Exercise 5: Manual pentesting with ZAP
  </h2>
  <p class='near-black'>
    On the <i>broken</i> branch, run ZAP manually to spider the app and
    then run an active scan against any URLs which look interesting. You could
    even experiment with using ZAP's fuzzer.
  </p>
  <p class='near-black'>
    There's no particular aim for this exercise. It's just about experimenting
    with ZAP to understand its capabilities.
  </p>
</div>
{% endblock content %}

notes/templates/write_note.html
{% extends 'base.html' %}
{% load static %}
{% load setclass %}

{% block pagename %}Write{% endblock pagename %}


{% block content %}
<form method='post' class="pa4 black-80 measure center">
  <fieldset id="sign_up" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Write a note</legend>
  {% csrf_token %}
  <div class='mt3'>
    <label for='receiver' class="db fw6 lh-copy f6">Receiver</label>
      {{ form.receiver | setclass:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class='mt3'>
    <label for='id_content' class="db fw6 lh-copy f6">Content</label>
      {{ form.content | setclass:'db border-box w-100 measure ba b--white-40 pa2 mb2'}}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class="">
    <input class="b mt2 ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id='send_button' type="submit" value="Send">
  </div>
</form>
{% endblock content %}